[mypy]
python_version = 3.12
check_untyped_defs = False
disallow_untyped_defs = False
ignore_missing_imports = True
warn_unused_ignores = True
warn_return_any = False
no_implicit_optional = True
show_error_codes = True
exclude = (?x)(
    ^custom_components/.*/manifest\.json$
)
